name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Update local.properties
        run: |
          echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" > local.properties

      - name: Display contents of local.properties
        run: cat local.properties

      - name: Build Android and Desktop Apps
        run: |
          ./gradlew clean
          ./gradlew :androidApp:assemble
          ./gradlew :desktopApp:assemble

      - name: Upload APK to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name: android-app
          path: androidApp/build/outputs/apk/juice_kadai.apk

      - name: Upload Desktop App to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name: desktop-app
          path: desktopApp/build/libs/juice_kadai.jar
